[package]
name = "alexandria_sorting"
version = "0.1.0"
description = "A set of sorting algorithms"
homepage = "https://github.com/keep-starknet-strange/alexandria/tree/src/sorting"
edition = "2023_11"

[tool]
fmt.workspace = true

[dependencies]
snforge_std.workspace = true
alexandria_data_structures = { path = "../data_structures" }
